- id: "{{ site.url }}"
  title: "Lights Of Tuscany 2019"
  img: "img/logo_lot19.svg"
  description: "Programme for international physics students in the VIRGO, LENS, INFN labs and Universities of Pisa and Florence"
  keywords: "aisf associazione italiana studenti di fisica iaps lot lights of tuscany pisa firenze"
